### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by kaizadp** [jianqiuz/3soilsdata#1]
2021-02-04
KP to-do 

1. 3Soils
- [ ] FTICR: all 3 suctions
   - [ ] ~get 15 kPa data~ *2/16/2021 update: only 1.5 and 50 kPa available for FTICR*
- [x] arrange by soil, treatment (?), suction, 
- [x] include element stoichiometry, compound classification

2. Bailey 2017 SBB
- [x] get raw data
- [x] rerun everything for consistent format?

**Comment by jianqiuz** [comment]
1. Email Bailey about 2017 SBB data
2. Create shared doc
